import SwiftUI

/// Card displaying budget status with progress bar
struct BudgetStatusCard: View {
    let budget: Budget

    var body: some View {
        VStack(alignment: .leading, spacing: DesignTokens.Spacing.xs) {
            HStack {
                Text(budget.categoryName)
                    .subheadlineStyle(color: DesignTokens.Colors.textPrimary)
                    .lineLimit(1)

                Spacer()

                if budget.isAutoGenerated {
                    Text("AUTO")
                        .font(.caption2)
                        .fontWeight(.bold)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 3)
                        .background(DesignTokens.Colors.stableBlue.opacity(0.2))
                        .foregroundColor(DesignTokens.Colors.stableBlue)
                        .cornerRadius(4)
                }

                Text(budget.status.rawValue.uppercased())
                    .font(.caption2)
                    .fontWeight(.bold)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(statusColor.opacity(0.2))
                    .foregroundColor(statusColor)
                    .cornerRadius(4)
            }

            VStack(alignment: .leading, spacing: DesignTokens.Spacing.xxs) {
                HStack {
                    Text(formatCurrency(budget.currentSpent))
                        .titleValueStyle()

                    Text("of \(formatCurrency(budget.monthlyLimit))")
                        .captionStyle()
                }

                GeometryReader { geometry in
                    ZStack(alignment: .leading) {
                        RoundedRectangle(cornerRadius: 4)
                            .fill(DesignTokens.Colors.borderMedium)

                        RoundedRectangle(cornerRadius: 4)
                            .fill(statusColor)
                            .frame(width: geometry.size.width * min(percentUsed / 100, 1.0))
                    }
                }
                .frame(height: 6)

                Text("\(formatCurrency(budget.remaining)) remaining")
                    .captionStyle()
            }
        }
        .padding(DesignTokens.Spacing.md)
        .frame(width: 200)
        .primaryCardStyle()
    }

    private var percentUsed: Double {
        guard budget.monthlyLimit > 0 else { return 0 }
        return (budget.currentSpent / budget.monthlyLimit) * 100
    }

    private var statusColor: Color {
        switch budget.status {
        case .onTrack: return DesignTokens.Colors.progressGreen
        case .caution: return DesignTokens.Colors.accentPrimary
        case .warning: return DesignTokens.Colors.opportunityOrange
        case .exceeded: return Color(red: 255/255, green: 59/255, blue: 48/255)
        }
    }

    private func formatCurrency(_ amount: Double) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.maximumFractionDigits = 0
        return formatter.string(from: NSNumber(value: amount)) ?? "$0"
    }
}

#if DEBUG
struct BudgetStatusCard_Previews: PreviewProvider {
    static var previews: some View {
        BudgetStatusCard(
            budget: Budget(
                id: UUID().uuidString,
                categoryName: "Groceries",
                monthlyLimit: 500,
                currentSpent: 350,
                isAutoGenerated: true
            )
        )
        .padding()
        .primaryBackgroundGradient()
    }
}
#endif
